### ISSUE TITLE
The Invincible Birds Strike Back (GitHub Issues II)

### ISSUE THREAD

**Issue by AnimatorJoe** [WestlakeAPC/flappy-smasher#14]
After the previous pull request, I have noticed that there are invincible birds again. In order to maintain the master branch as fully functional, I will revert to the latest commit. This issue can be reproduced by moving the character to the lowest possible position, and then fire swords out constantly. The birds also spawn very far away from the visible user interface, and results in the killing of birds that have not yet shown up. We must fix this issue as soon as possible.

**Comment by EtherTyper** [comment]
For reference:
- Previous PR was #7, moved SKNode initialization to the static file FlappySlicer/GameScene.sks
- Invincible birds is a known and existing issue, which apparently wasn't permanently fixed properly.
- I've made the birds spawn _**much**_ closer to the screen in PR #15.
